services:
  delta-sharing-server:
    platform: linux/amd64
    image: deltaio/delta-sharing-server:0.7.8
    container_name: delta-sharing-server
    build:
      context: ./delta
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin@123
    ports:
      - "8080:8080"
    networks:
      - delta_network
    depends_on:
      - minio
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin@123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    networks:
      - delta_network
    command: server /data --console-address ":9001"
  jupyterlab:
    build:
      context: ./jupyterlab
      dockerfile: Dockerfile
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./jupyterlab/notebooks:/home/jovyan/work
    networks:
      - delta_network
    depends_on:
      - delta-sharing-server
networks:
  delta_network:
    driver: bridge
